[package]
name = "Dex-Aggregator"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.1.2", features = ["providers"] }
alloy-transport-ws = "1.1.2"
tokio = { version = "1.48.0", features = ["full", "sync"] }
